name: master-push-action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.6.0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.6.0
      with:
        version: "14.0"
    - name: Check code formatting
      run: |
        clang-format --style=file -n --Werror *.cpp *.h &> formattingReport.txt || true
        FORMATTING_REPORT="$(cat formattingReport.txt)"
        cat formattingReport.txt
        clang-format -n --Werror noSuchFile &> noSuchFileExample.txt || true
        NO_SUCH_FILE_EXAMPLE="$(cat noSuchFileExample.txt)"
        clang-format -n --Werror noSuchFile noSuchFile &> doubleNoSuchFileExample.txt || true
        DOUBLE_NO_SUCH_FILE_EXAMPLE="$(cat doubleNoSuchFileExample.txt)"
        if [[ $FORMATTING_REPORT != $NO_SUCH_FILE_EXAMPLE && $FORMATTING_REPORT != $DOUBLE_NO_SUCH_FILE_EXAMPLE ]]; then
          exit 1
        fi
    - name: Check code compilability
      run: clang++ --std=c++14 Main.cpp
    - name: Check code linting
      run: clang-tidy Main.cpp
    - name: Compute code complexity
      run: |
        clang++ -Xclang -ast-dump -fsyntax-only Main.cpp > ast.txt || true
        wc -l ast.txt | awk '{print "Current code complexity:",$1;}'
